### PR TITLE
[ feature ] Completion request

### LINKED ISSUE #139: Support Completion Request
[Completion Request Spec](https://microsoft.github.io/language-server-protocol/specification#textDocument_completion)

### PR DESCRIPTION
**Pull request by andorp**
Resolves #139 

The Completion list resolution is purely syntactical. It is based on the identifier around the cursor. 

The main problem I had to solve was maintaining the document's unsaved version, which I call as VirtualDocument. I tested this version implementing the CallHiearchy, and it felt smooth on my low-end machine. My original approach involved more dependent types and linear scans of strings, but that obscured the readability. Hence, I settled down with the simple lines/unlines approach, which introduces a bit of inconsistency around newlines and needs fixing. 

The suggestions are syntactical based on the cursor's position and around the identifier. The implementation doesn't distinguish between expression and non-expression context and renders completion everywhere in the file, even in comments and import lines. The main reason for this is that every DidChange notification invalidates some part of the LSP context, and there is no way to know what Idris thinks about the position of that cursor. Having the location information would be a bigger refactor I wanted to avoid introducing in this change, as the completion already feels useful. 

The recipe for such a refactor is the following;

- For every `DidChange`, the LSP could maintain a `Pos -> Maybe Pos` transformation, which maps the virtual document position to the position of the original document
- The LSP shouldn't invalidate the context at every change. Information from the `Context` environment and `Metadata` could be reused to determine what the completion needs to know about the typing context.

Possible improvements and low-hanging fruits for future work:

- The content of the VirtualDocument could be stored in an IORef rather than in the configuration state. It would make the config state lighter when updating its content.
- The completion list generation is purely syntactical; it generates suggestions everywhere (including import lines and comments), not in just expression context.
- When the user types `.`, only the field accessors should be rendered in the list.
- Suggest more in further tickets... :)

### CODE REVIEW

**Comment by andorp** [comment]
Completion request in action:
For short names, it renders local to module definitions. It picks up user-defined parameter names and adds holes and parenthesis around function calls.
[CompletionDemoParenthesisAndHoles.webm](https://user-images.githubusercontent.com/3465327/226132232-2ec4b584-2a87-48ae-be8c-343df90a7475.webm)

**Comment by andorp** [comment]
The completion list shows the type and the documentation:
[CompletionDemoDocumentationAndTypes.webm](https://user-images.githubusercontent.com/3465327/226132629-7b7fa5f4-d9b9-42b4-81c3-aed88fd65349.webm)

**Comment by andorp** [comment]
One annoying thing demonstrated on the screen capture is that we can also pick functions that don't fit the typing context.

**Review by ShinKage — APPROVED** [review]

**Review by michaelmesser — APPROVED** [review]

**Comment by andorp** [comment]
Thanks for the approvals.

**Comment by Russoul** [comment]
The two webm links don't load up for me :(

**Comment by andorp** [comment]
They still load for me.

**Pull request merged**
