### PR TITLE
REPL integration

### PR DESCRIPTION
**Pull request by Russoul**
Very straightforward REPL integration via a custom LSP command `repl`, that takes a string argument to be directly fed into a REPL instance. The result is returned to the client directly, as a string. Colours are turned off for the output generated by REPL.

### CODE REVIEW

**Comment by andorp** [comment]
Is there a way to test this with VSCode?

**Comment by michaelmesser** [comment]
I believe this requires changes to the editor plugin to be usable in VSCode.

**Comment by andorp** [comment]
I see.

**Comment by Russoul** [comment]
Unfortunately, the changes are indeed required. And yes, the state would be lost, AFAIK, because LSP just reloads everything when one opens a new file. It's still very useful in the current state, because commands like `ti`, `m` and `fs` can be invoked directly. We'll create a new repo with an updated Neovim config.

Regarding VS code, here I am powerless, because I have almost 0 knowledge of it

**Comment by michaelmesser** [comment]
You can make an issue at https://github.com/bamboo/idris2-lsp-vscode

**Pull request merged**
